In [47]:
import numpy as np

# Create a 3x3 matrix array with values ranging from 2 to 10
matrix = np.arange(2, 11).reshape(3, 3)
print("3x3 Matrix with values from 2 to 10:\n", matrix)

3x3 Matrix with values from 2 to 10:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
import numpy as np

# Take input from the user
user_input = input("Enter values separated by spaces: ")

In [ ]:
# Convert input to a list of integers
int_array = np.array(user_input.split(), dtype=int)

In [ ]:
# Convert the integer array to float type
float_array = int_array.astype(float)
print("Array converted to float type:", float_array)


In [ ]:
import numpy as np

# Original array
original_array = np.array([10, 20, 30])

In [ ]:
# Values to append
values_to_append = np.array([40, 50, 60, 70, 80, 90])

In [ ]:
# Append values to the end of the array
new_array = np.append(original_array, values_to_append)
print("Array after appending values:", new_array)

In [ ]:
import numpy as np

# Create two NumPy arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

In [ ]:
# Add the elements of both arrays
sumArray = np.add(array1, array2)
print("Sum of the two arrays:", sumArray)

In [ ]:
import numpy as np

# Create a 3x3 array with values from 10 to 90 (interval of 10)
array1 = np.arange(10, 100, 10).reshape(3, 3)
print("3x3 Array with values from 10 to 90:\n", array1)

In [ ]:
# a. Extract the 1st row from the array
first_row = array1[0, :]
print("1st row of the array:", first_row)

In [ ]:
# b. Extract the last element from the array
last_element = array1[-1, -1]
print("Last element of the array:", last_element)